name: Test PowerShell on Ubuntu

on:
  push:
    branches:
      - main 
      - release/*
  pull_request:
    branches: [ master ]

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download BFlat
        shell: pwsh
        run: ./scripts/download-bflat.ps1


      # - name: Run PS Script Analyzer
      #   shell: pwsh
      #   run: |
      #     Invoke-ScriptAnalyzer -Path . -Recurse -ExcludePath .\tests\* -Severity Error,Warning -EnableExit
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester tests/BinWips.Tests.ps1 -Passthru
        