name: Test PowerShell on Ubuntu

on:
  push:
    branches:
      - main 
      - release/*
  pull_request:
    branches: [ master ]

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name : Check module manifest
        shell: pwsh
        run: |
          Test-ModuleManifest -Path ./src/Modules/BinWips/BinWips.psd1
      - name: Run PS Script Analyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./src -Recurse -Severity Error,Warning -EnableExit
      - name: Download BFlat
        shell: pwsh
        run: ./tools/download-bflat.ps1
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester tests/BinWips.Tests.ps1 -Passthru | Export-CliXml -Path Unit.Tests.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-Unit-Tests
          path: Unit.Tests.xml
      - name: Publish PowerShell Module to github packages
        uses: natescherer/publish-powershell-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: packages
          path: src/Modules/BinWips